apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
  labels:
    app: webapp
spec:
  restartPolicy: Always
  containers:
  - name: webapp
    image: 027008469250.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:webapp-v0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.database"
    - name: DBPORT
      value: "3306"
    - name: DATABASE
      value: "employees"
    - name: DBUSER
      value: "db_user"
    - name: DBPWD
      value: "db_password"
  imagePullSecrets:
  - name: ecr-secret