apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 027008469250.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:webapp-v0.3
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service.database.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DATABASE
              value: "employees"
            - name: DBUSER
              value: "db_user"
            - name: DBPWD
              value: "db_password"